### ISSUE TITLE
Create GitHub workflow/action that automatically re-generates a asciinema file (and .gif)

### ISSUE THREAD

**Issue by rugk** [k9withabone/autocast#2]
## Use case
The problem this tool solves is that cumbersome re-generating of custom asciinema CLI shows once your CLI tool changes etc. This solves a very annoying task. It automates this.

What if we take this paradigm even further?
Can't we create a GitHub workflow to automate it after each change (or tag if CLI output rarely changes and you want to save resources etc.?)  For this project it would be a good try?
Going even further, what if [why not just create a GitHub Action](https://docs.github.com/en/actions/creating-actions), so other's can use this, too?

## Solution
The GitHub Action should:
* generate a new asciinema file
* optionally upload/update it on the asciinema website
* generate a gif out of it (or is there some Asciinema or other good GitHub Action or so for this already?)

With https://github.com/EndBug/add-and-commit/ the files could in your workflow then automatically be committed in the repository and a bot would automatically update your preview.

Problem: Do asciinema links need to be replaced? If so, ideally it should do this, too – though that would be cumbersome obviously? But if not, the better, then a link can stay stable.

**Comment by k9withabone** [comment]
GitHub actions are not my forte. If you create one using autocast let me know, and I'll add a link to it on the README. I know there is [taiki-e/install-action](https://github.com/taiki-e/install-action) for installing things via [cargo-binstall](https://github.com/cargo-bins/cargo-binstall) which is supported for installing autocast.

I create asciicast GIFs with [agg](https://github.com/asciinema/agg). 

> Problem: Do asciinema links need to be replaced? If so, ideally it should do this, too – though that would be cumbersome obviously? But if not, the better, then a link can stay stable.

I don't believe there is a way to replace an existing asciicast in place on [asciinema.org](https://asciinema.org/). As a workaround you could set up a simple redirect service to keep the link stable and then update the redirect when creating a new recording. You also might try asking for help on the [asciinema matrix channel](https://matrix.to/#/#asciinema:matrix.org), they are a friendly bunch :smile: .
