### ISSUE TITLE
Would this work with PowerSession-rs?

### ISSUE THREAD

**Issue by nmstoker** [k9withabone/autocast#3]
I haven't got a firm handle on how autocast gets the results it does, so perhaps this is a naive question, but would this tool possibly work with the repo https://github.com/Watfaq/PowerSession-rs which is an asciinema clone able to run on Windows?

---
Thanks a lot for this tool - I realised the need for something exactly like this when I started trying to set up a range of asciinema recordings recently for documentation I was sprucing up.

**Comment by k9withabone** [comment]
Autocast theoretically should work just fine on Windows. I haven't really tested this though as I don't use Windows myself anymore.

Autocast doesn't use asciinema under the hood. It creates an asciicast file directly by starting a shell in a PTY using the [expectrl](https://crates.io/crates/expectrl) library, then by running commands via the started shell. Bash is used as the default, so you'll have to customize the shell configuration to get autocast to work on Windows. See the [`full-example.yaml` file, starting at line 24](https://github.com/k9withabone/autocast/blob/b351ecaf550457dabb7e01ef65360fc5949cb100/full-example.yaml#L24-L70), for configuring the shell. The bash defaults are set [here in the code](https://github.com/k9withabone/autocast/blob/b351ecaf550457dabb7e01ef65360fc5949cb100/src/config/spawn.rs#L22-L51) if that helps.

If you get something working let me know, and I'll add it as a `--shell` option. However, it might just be easier to just use WSL.

The asciicast files autocast creates should work just fine with Power Session, assuming it has kept up with the semi-recent additions to the format, notably the [marker event type](https://docs.asciinema.org/manual/asciicast/v2/#m-marker) if you use the [`!Marker` instruction](https://github.com/k9withabone/autocast/blob/b351ecaf550457dabb7e01ef65360fc5949cb100/full-example.yaml#L200-L203).

By the way, asciinema is currently being rewritten in Rust. So maybe it will work on Windows at some point?

**Comment by nmstoker** [comment]
Thanks! Really appreciate the answer with all those handy pointers.

I'll see what I can come up with!

Good point re: asciicast being rewritten too.
