### ISSUE TITLE
Alternatives

### ISSUE THREAD

**Issue by rugk** [k9withabone/autocast#7]
In https://github.com/borgbackup/borg/issues/8040 I asked some project maintainers to switch to your solution, but it appears to be kissing one important requirement: isolation e.g. in containers or VMs.

That said, that's okay for this project IMHO. Maybe it can be listed in the Readme though?

Alternatives mentioned:
> At a quick glance autocast appears to be a tool with a similar purpose to [TCL expect](https://core.tcl-lang.org/expect/index) (which I used). Both allow automated control of software that requires a terminal emulator (TTY). Autocast appears to be more special-purpose. There is a chance a more special-purpose tool can be an improvement over a more general-purpose tool.

https://github.com/borgbackup/borg/issues/8040#issuecomment-2031233985

Maybe add some doc?

**Comment by hexagonrecursion** [comment]
1. "kissing" -> missing? typo?
2. As far as I understand autocast can probably run in containers and VMs too. My argument was that autocast can't _replace_ Vagrant for our use-case - just like expect it would need to be used inside a container and/or VM

**Comment by k9withabone** [comment]
Alternatives are sort of already in the "Inspiration" section of the README. [`expectrl`](https://crates.io/crates/expectrl) is listed there and if you look at the bottom of its README, they list [`rexpect`](https://crates.io/crates/rexpect) and [pexpect](https://pexpect.readthedocs.io/en/stable/overview.html) as inspiration.

**Comment by k9withabone** [comment]
I think this can be closed unless there are other suggestions for alternatives. You might also want to check out asciinema's [integrations page](https://docs.asciinema.org/integrations/).
