### ISSUE TITLE
Version 0.1.0 hangs

### ISSUE THREAD

**Issue by chip** [k9withabone/autocast#8]
Hello - Thanks for creating this code!

I am running into an issue where autocast never produces an OUT_FILE, it just hangs instead:

    autocast --overwrite example.yml example.cast
    Read from file: example.yml

I've also tried `demo.yml` and `full-example.yml` *(with and without --overwrite option)* from your **README** with the same results. I'm running MacOS Ventura 13.4 (M2 chip). I normally use **zsh**, but setup a minimal `~/.bashrc` since that is the default shell being used per the docs.

If you have any suggestions, I'd be grateful. Happy to provide more details about my setup if that would help. Thanks again. 😄

**Comment by k9withabone** [comment]
Is bash aliased to zsh? If so you should remove that and actually install bash if you want to continue to use the defaults. I don't think [the bash setup](https://github.com/k9withabone/autocast/blob/8304dd25c4fa7e4b18d05b1ce3997eb5833189b9/src/config/spawn.rs#L22-L51) is compatible with other shells. You shouldn't be able to use the `--shell bash` (the default) option without having bash available in your `PATH`. Autocast should error if the shell process can't be spawned.

You might want to try to set up zsh as a [custom shell](https://github.com/k9withabone/autocast/blob/b351ecaf550457dabb7e01ef65360fc5949cb100/full-example.yaml#L24-L70), see also #1. If you get this working please share it, so I can add it as a built-in option. I don't have any familiarity with shells other than bash and a bit of nushell.

**Comment by chip** [comment]
Thanks for the suggestions. I'll close this for now.
